version: '3.8'

services:
  # --- API FLASK ---
  app:
    build: .
    container_name: api-flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=devsecops_db
    depends_on:
      - db

  # --- BASE DE DATOS MYSQL ---
  db:
    image: mysql:8.0
    container_name: servidor-bd-ejemplo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devsecops_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # --- UPTIME KUMA (MONITOREO) ---
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime_kuma_data:/app/data

  # --- DOZZLE (LOGS EN VIVO) ---
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Credenciales exigidas por la guía: ProfeChristian / Evidencia2
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_NO_ANALYTICS=true

volumes:
  mysql_data:
  uptime_kuma_data: